allow-branch = ["main"]
push = true
consolidate-commits = true
shared-version = true
tag-name = "v{{version}}"
tag-message = "Release {{version}}"
pre-release-commit-message = "build: release - {{version}}"
publish = false
